/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/old_computer.glb -o src/components/gltf/ComputerModel.jsx -r public 
Author: SketchyBot (https://sketchfab.com/SketchyB0t_3D_Fabrication)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-computer-bf6636fcc0954752bc9ffb5cec581b7f
Title: Old Computer
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

type Props = {};

export function ComputerModel(props: Props) {
  const { materials, nodes } = useGLTF('/Models/old_computer.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 5, 175]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube003_Keyboard_0.geometry} material={materials.Keyboard} />
          <mesh geometry={nodes.Cube003_Mouse_0.geometry} material={materials.Mouse} />
          <mesh geometry={nodes.Cube003_Tower_0.geometry} material={materials.Tower} />
          <mesh geometry={nodes.Cube003_Monitor_0.geometry} material={materials.Monitor} />
          <mesh geometry={nodes.Cube003_Screen_0.geometry} material={materials.Screen} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/Models/old_computer.glb');
